name: Example deploy workflow

on:
  push:

jobs:

  weblate_push:

    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script files executable
        run: chmod +x weblate_push.sh
      - name: Run deployment
        run: ./weblate_push.sh

  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script files executable
        run: chmod +x deploy.sh
      - name: Run deployment
        run: ./deploy.sh
