name: Example deploy workflow

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run deployment
        run: ./deploy.sh
